# Generated by Django 5.2.14 on 2026-06-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donations', '0002_blogpost_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=500)),
                ('answer', models.TextField()),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'verbose_name': 'FAQ',
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='gallery/')),
                ('caption', models.CharField(blank=True, default='', max_length=300)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordering', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, default='', max_length=400)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone_primary', models.CharField(blank=True, default='', max_length=30)),
                ('phone_secondary', models.CharField(blank=True, default='', max_length=30)),
                ('whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('office_hours', models.CharField(blank=True, default='', max_length=200)),
                ('maps_embed_url', models.TextField(blank=True, default='')),
                ('social_facebook', models.URLField(blank=True, default='')),
                ('social_instagram', models.URLField(blank=True, default='')),
                ('social_linkedin', models.URLField(blank=True, default='')),
                ('pvo_number', models.CharField(blank=True, default='', max_length=50)),
                ('trust_deed', models.CharField(blank=True, default='', max_length=50)),
                ('cert_image', models.ImageField(blank=True, null=True, upload_to='site/cert/')),
                ('cert_caption', models.CharField(blank=True, default='', max_length=200)),
                ('cert_description', models.TextField(blank=True, default='')),
                ('stat_years', models.CharField(blank=True, default='', max_length=20)),
                ('stat_districts', models.CharField(blank=True, default='', max_length=20)),
                ('stat_score', models.CharField(blank=True, default='', max_length=20)),
            ],
            options={
                'verbose_name': 'Site Settings',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('member_type', models.CharField(choices=[('board', 'Board Member'), ('staff', 'Staff Member')], default='staff', max_length=10)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='team/')),
                ('bio', models.TextField(blank=True, default='')),
                ('experience_years', models.PositiveIntegerField(blank=True, null=True)),
                ('qualifications', models.TextField(blank=True, default='', help_text='One qualification per line.')),
                ('contact_whatsapp', models.CharField(blank=True, default='', max_length=30)),
                ('contact_phone', models.CharField(blank=True, default='', max_length=30)),
                ('ordering', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Testimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('title', models.CharField(max_length=200)),
                ('location', models.CharField(blank=True, default='', max_length=200)),
                ('quote', models.TextField()),
                ('rating', models.PositiveSmallIntegerField(default=5)),
                ('is_active', models.BooleanField(default=True)),
                ('ordering', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['ordering', 'name'],
            },
        ),
    ]
